Fix dynamic version treatment in the RPM SPEC file
The error without this change looks like:

Error: The version in the Python package metadata 0.0.0 normalizes to zero.
It's likely a packaging error caused by missing version information
(e.g. when using a version control system snapshot as a source).
Try providing the version information manually when building the Python package,
for example by setting the SETUPTOOLS_SCM_PRETEND_VERSION environment variable if the package uses setuptools_scm.
If you are confident that the version of the Python package is intentionally zero,
you may %define the _python_dist_allow_version_zero macro in the spec file to disable this check.

error: Dependency tokens must begin with alpha-numeric, '_' or '/': *** PYTHON_PROVIDED_VERSION_NORMALIZES_TO_ZERO___SEE_STDERR ***
Provides: python-aexpect = 1.8.0-1.fc42 python3-aexpect = 1.8.0-1.fc42 python3.13-aexpect = 1.8.0-1.fc42
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PartialHardlinkSets) <= 4.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /usr/bin/python3 python(abi) = 3.13
    bogus date in %changelog: Tue Feb 28 2022 Lucas Meneghel Rodrigues <lmr@amazon.com> - 1.7.0-1
    bogus date in %changelog: Tue Feb 28 2022 Lucas Meneghel Rodrigues <lmr@amazon.com> - 1.7.0-1
    Dependency tokens must begin with alpha-numeric, '_' or '/': *** PYTHON_PROVIDED_VERSION_NORMALIZES_TO_ZERO___SEE_STDERR ***

Signed-off-by: Plamen Dimitrov <plamen.dimitrov@intra2net.com>